"""Short, easy-to-type words for access tokens that are friendly on a phone keyboard."""

WORDS = (
    'agate', 'almond', 'amber', 'anchor', 'apple', 'aspen', 'atlas', 'badger', 'bamboo', 'banjo',
    'barrel', 'basket', 'beacon', 'bell', 'berry', 'birch', 'bison', 'blanket', 'blue', 'boots',
    'bowl', 'brave', 'bread', 'breeze', 'brick', 'bridge', 'bright', 'brook', 'bucket', 'butter',
    'button', 'cabin', 'calm', 'camel', 'candle', 'canopy', 'canyon', 'castle', 'cedar', 'chair',
    'clever', 'cliff', 'clock', 'cloud', 'clover', 'cocoa', 'comet', 'compass', 'copper', 'coral',
    'cosy', 'cotton', 'crab', 'creek', 'cup', 'daisy', 'dawn', 'delta', 'desert', 'down', 'drift',
    'drum', 'dusk', 'dust', 'eagle', 'east', 'echo', 'ember', 'engine', 'falcon', 'fancy', 'far',
    'fern', 'fiddle', 'finch', 'flint', 'flute', 'forge', 'fork', 'fox', 'frost', 'galaxy',
    'garden', 'gecko', 'gentle', 'ginger', 'glass', 'glove', 'gold', 'granite', 'green', 'guitar',
    'hammer', 'happy', 'harbor', 'hare', 'harp', 'haven', 'heron', 'high', 'hollow', 'honey',
    'humble', 'igloo', 'indigo', 'iron', 'island', 'ivory', 'jacket', 'jade', 'jigsaw', 'jolly',
    'jungle', 'kernel', 'kettle', 'kind', 'kitten', 'knife', 'koala', 'ladder', 'lagoon', 'lake',
    'lamp', 'lantern', 'left', 'lemon', 'lily', 'linen', 'lively', 'llama', 'long', 'low', 'lucky',
    'lunar', 'lynx', 'magnet', 'mango', 'maple', 'marble', 'market', 'mauve', 'meadow', 'mellow',
    'merry', 'mirror', 'moon', 'moose', 'moss', 'mouse', 'narrow', 'near', 'nectar', 'noble',
    'noodle', 'north', 'ocean', 'ochre', 'olive', 'onyx', 'opal', 'orange', 'orchard', 'otter',
    'oyster', 'panda', 'paper', 'peach', 'pearl', 'pecan', 'pencil', 'pepper', 'piano', 'pillow',
    'plate', 'plum', 'pond', 'poppy', 'prairie', 'proud', 'puzzle', 'quartz', 'quick', 'quiet',
    'quiver', 'rabbit', 'rain', 'raven', 'red', 'reed', 'ribbon', 'ridge', 'right', 'river',
    'robin', 'rocket', 'ruby', 'saddle', 'sand', 'scarf', 'scarlet', 'seal', 'sepia', 'sesame',
    'shark', 'short', 'silk', 'silver', 'slate', 'snail', 'snow', 'solar', 'south', 'sparrow',
    'spoon', 'squid', 'star', 'steel', 'stone', 'storm', 'summit', 'sunny', 'swan', 'swift',
    'table', 'teal', 'thunder', 'tide', 'tiger', 'tin', 'tower', 'trout', 'trumpet', 'tulip',
    'valley', 'velvet', 'village', 'violet', 'violin', 'wagon', 'walnut', 'walrus', 'wander',
    'wave', 'west', 'whale', 'whistle', 'wide', 'willow', 'window', 'witty', 'wolf', 'wood', 'wool',
    'yellow', 'yonder', 'zebra', 'zephyr',
)
